all:
  children:
    k3s_server:
      hosts:
        k3s-master-01:
          ansible_host: 192.168.5.40
    k3s_agents:
      hosts:
        k3s-worker-01:
          ansible_host: 192.168.5.41
        k3s-worker-02:
          ansible_host: 192.168.5.42
        k3s-worker-03:
          ansible_host: 192.168.5.43